import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import "@/styles/globals.css";

export const metadata = {
  title: "Adetunji Marvellous",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black-pry">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
